version: '3.7'
services:
  gourmet-db:
    image: gourmet-db:v1
    container_name: docker-gourmet-db-mysql
    restart: always
    networks:
     - springcloud
    #environment: 
      #MYSQL_DATABASE: db_gourmet
      #MYSQL_ROOT_PASSWORD: admin

  gourmet-api:
    image: gourmet-api:v1
    container_name: docker-gourmet-api
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      WAIT_HOSTS: docker-gourmet-db-mysql:3306
    networks:
      - springcloud
    depends_on: 
      - gourmet-db

  gourmet-web:
    image: gourmet-web:v1
    container_name: docker-gourmet-web
    ports:
      - "5500:80"
    #restart: always
    restart: always
    networks:
      - springcloud
    #depends_on: 
      #- gourmet-db
      #- gourmet-api
