apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: gourmet-web
  name: gourmet-web
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: gourmet-web:v1
    generation: null
    importPolicy: {}
    name: v1
status:
  dockerImageRepository: ""
